### ISSUE TITLE
1.19 Supported?

### ISSUE THREAD

**Issue by MayhemBill** [BlackBeltPanda/Essentials-Kits-To-CMI#2]
Howdy, it's been over a year since last update, and I just wanted to find out if 1.19 and latest CMI/Essentials were supported?

**Comment by MayhemBill** [comment]
I get this issue when attempting to run the plugin

```
[EssentialsKitsToCMI] Enabling EssentialsKitsToCMI v1.1
java.lang.Exception: §4That kit does not exist.
        at EssentialsX-2.20.0-dev+17-6e931b2.jar//com.earth2me.essentials.Kit.<init>(Kit.java:43)
        at EssentialsKitsToCMI.jar//main.java.BlackBeltPanda.EssentialsKitsToCMI.EssentialsKitsToCMI.onEnable(EssentialsKitsToCMI.java:27)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
